version: '3.7'

services:
  postgres:
    container_name: postgres-admin
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=CHANGE-ME
      - PGADMIN_DEFAULT_PASSWORD=CHANGE-ME
    ports:
      - 5082:80
      - 5543:443
    volumes:
      - /storage/var/lib/pgadmin:/var/lib/pgadmin
    networks:
      - lan-network

networks:
   lan-network:
      external:
         name: docker-lan